{
 "title": "Backend",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend\"}) by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod UP Time",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(up{container=~\"backend|frontend\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container=~\"backend|frontend\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum{container=~\"backend|frontend\"} / flask_http_request_duration_seconds_count{container=~\"backend|frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend\", status=~\"5.*|4.*\"})/sum(flask_http_request_total{container=~\"backend|frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(flask_http_request_duration_seconds_sum{container=~\"backend|frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}