{
 "title": "Backend",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage Per Pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"backend.*|frontend.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Per Pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_memory_usage_bytes{pod=~\"backend.*|frontend.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{container=~\"backend|frontend\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by(container) (kube_pod_container_status_running{pod=~\"backend.*|frontend.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Share of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{container=~\"backend|frontend\", status=~\"5.*|4.*\"})/sum(flask_http_request_total{container=~\"backend|frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max(flask_http_request_duration_seconds_sum{container=~\"backend|frontend\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}